---
deployment:
  tasks:
    - export REPO_PATH=/home/ppdcorg/repositories/gwapp3.1-client
    - export DEPLOYPATH=/home/ppdcorg/public_html/gwapp3-1
    - cd $REPO_PATH
    - npm install
    - npm run build
    - /bin/cp -R * $DEPLOYPATH