deployment:
  tasks:
    - export APP_PATH=/home/ppdcorg/public_html/gwapp3
    - export REPO_PATH=/home/ppdcorg/repositories/gwapp3
    - cd $REPO_PATH
    - npm install
    - npm run build
    - /bin/cp -R $REPO_PATH/build/* $APP_PATH
